---
driver:
  name: docker
  use_sudo: false
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      image: ubuntu:12.04
  - name: centos-6.4
    driver_config:
      image: centos:6.4

suites:
  - name: package
    run_list:
      - recipe[hyone_tmux-test::package]
    attributes:
  - name: source
    run_list:
      - recipe[hyone_tmux-test::source]
    attributes:
      hyone_tmux:
        user: hoge
        group: hoge
        libevent_version: "2.0.21-stable"
        version: "1.8"
